In [3]:
import numpy as np
import matplotlib.pyplot as plt
import math
import torch

import cv2
from ultralytics import YOLO

from src.pworld import *
from src.pnn import *

In [ ]:
### Tracking 
### Ref: https://docs.ultralytics.com/modes/track/#configuration
### 

# Load the YOLO11 model
model = YOLO("model/yolo11s.pt")
ToTrack = False

# Open the video file
video_path = "test/ext.webm"
cap = cv2.VideoCapture(video_path)  

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLO11 tracking on the frame, persisting tracks between frames
        if ToTrack:
            results = model.track(frame, persist=True, classes=[32])
        else:
            results = model.predict(frame, classes = [32])

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLO11 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

In [ ]:
# edit and crop a video
# Open the video file
video_path = "test/ext.webm"
cap = cv2.VideoCapture(video_path)
if cap.isOpened():
    print("number of frames =", int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
    print("time per frame =", cap.get(cv2.CAP_PROP_FPS))
    tags = [cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT] 
    w, h = [int(cap.get(t)) for t in tags]
    print("frame dimension = {}, {}".format(w, h) )

cap.release()

number of frames = 6373
time per frame = 25.0
frame dimension = 1280, 720


In [ ]:
t1 = [[203.99984741210938, 550.3505859375, 252.66238403320312, 614.80029296875],
    [1121.1800537109375, 663.15478515625, 1249.0103759765625, 718.875]]
t2 = [[992.316162109375, 602.4058837890625, 1098.7041015625, 703.0634765625]]
t1 = torch.tensor(t1)
t2 = torch.tensor(t2)
print( t1 - t2)
a = t1 - t2
b = torch.sum(a**2, axis = 1)
k = torch.topk(-b, 1).indices.item()
print(b,k)

c = t1[k, :]
print(c.unsqueeze(0))
print(t1.flatten().tolist())

tensor([[-788.3163,  -52.0553, -846.0417,  -88.2632],
        [ 128.8639,   60.7489,  150.3063,   15.8115]])
tensor([1347729.3750,   43138.3125]) 1
tensor([[1121.1801,  663.1548, 1249.0104,  718.8750]])
tensor([ 203.9998,  550.3506,  252.6624,  614.8003, 1121.1801,  663.1548, 1249.0104,  718.8750])
